version: '3.8' 
services:
  jenkins-controller: 
    # Build docker image to install required plugins
    build: .  
    container_name: jenkins-controller
    environment:
      # Docker env
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1

      # Jenkins admin and non-admin credential variables
      - JENKINS_ADMIN_ID=${ENV_JENKINS_ADMIN_ID} 
      - JENKINS_ADMIN_PASSWORD=${ENV_JENKINS_ADMIN_PASSWORD}
      - JENKINS_CI_ID=${ENV_JENKINS_CI_ID} 
      - JENKINS_CI_PASSWORD=${ENV_JENKINS_CI_PASSWORD}

      # Jenkins setup, configration as code
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ./casc.yaml:/var/jenkins_home/casc.yaml

  docker-dind: 
    container_name: jenkins-docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    image: docker:dind
    links:
      - "jenkins-controller:docker"
    networks:
      - jenkins
    ports:
      - "2376:2376"
    privileged: true
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

networks:
  jenkins:
    name: jenkins

volumes:
  jenkins-data:
  jenkins-docker-certs: